name = "x402-task-board"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "6a0bf22a5ff120f19789f29eb4196ce2"

[[d1_databases]]
binding = "DB"
database_name = "x402-task-board"
database_id = "3b2f9d5f-c22e-4803-8cda-57865f5aa343"

[vars]
CORS_ORIGIN = "*"
